openapi: 3.0.0
info:
  title: My Coffee API
  description: This is a full documentation API for My Coffee.
  version: 1.0.0
servers:
  - url: /api
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /login:
    post:
      summary: User login
      tags:
        - AUTH
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: newuser@gmail.com
                password:
                  type: string
                  example: newpassword
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful, returns a token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Success"
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJ1c2VyX2lkIjogNiwgInVzZXJfbG9naW4iOiAiYWRtQGdtYWlsLmNvbSJ9
        '400':
          description: Invalid credentials or other error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid credentials"
                  data:
                    type: object
                    example: {}

  /register:
    post:
      summary: User registration
      tags:
        - AUTH
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: newuser@gmail.com
                password:
                  type: string
                  example: newpassword
                name:
                  type: string
                  example: My Company
                logo:
                  type: string
                  format: binary
                  description: "Company logo file"
              required:
                - email
                - password
                - name
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Registration successful"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: newuser@gmail.com
                      name:
                        type: string
                        example: My Company
                      logo:
                        type: string
                        example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
        '400':
          description: Registration failed or email already registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email already registered"
                  data:
                    type: object
                    example: {}

  /events:
    post:
      summary: Create a new event
      security:
        - ApiKeyAuth: []
      tags:
        - Events
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Tech Conference
                date_end:
                  type: string
                  example: "2024-09-01 09:00:00"
                date_begin:
                  type: string
                  example: "2024-09-01 12:00:00"
                date_tz:
                  type: string
                  example: "Asia/Jakarta"
                seats_limited:
                  type: boolean
                  example: true
                seats_max:
                  type: integer
                  example: 100
                badge_image:
                  type: string
                  format: binary
                  description: "Badge image file"
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event created successfully"
                  data:
                    type: object
        '400':
          description: Error in creating event
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data"
                  data:
                    type: object
                    example: {}
    get:
      summary: Get a new event
      security:
        - ApiKeyAuth: []
      tags:
        - Events
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event created successfully"
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Tech Conference
                      date_end:
                        type: string
                        example: "2024-09-01 09:00:00"
                      date_begin:
                        type: string
                        example: "2024-09-01 12:00:00"
                      organizer_id:
                        type: integer
                        example: 1
                      address_id:
                        type: string
                        example: 16
                      date_tz:
                        type: string
                        example: "Asia/Jakarta"
                      seats_limited:
                        type: boolean
                        example: true
                      seats_max:
                        type: integer
                        example: 100
                      badge_image:
                        type: string
                        format: binary
                        description: "Badge image file"
        '400':
          description: Error in creating event
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data"
                  data:
                    type: object
                    example: {}
